---
title: "Data Description"
---

##Parkinsons Telemonitoring Data Set
###About the Data
The ML Dataset that I have chosen is the "Oxford Parkinson's Disease Telemonitoring Dataset" from the University of California Irvine Machine Learning Repository.

The dataset is composed of various biomedical voice measurements from 42 people with early-stage Parkinson's disease to a clinical trial of a telemonitoring device. There are 5875 observations, and a total of 26 different features. The goal of this data is to predict motor and total UPDRS scores for each observation using the voice metrics in the dataset. A link to the full description of the dataset, and more information on the features can be found [here.](http://archive.ics.uci.edu/ml/datasets/Parkinsons+Telemonitoring)

###Why I chose this set
I chose this dataset because it is in the domain of life sciences, is well structured clinical data for regression analysis, and can be used to both predict an outcome and to understand which metrics may be most influenctial when tracking UPDRS scores for people with Parkinson's disease. This set also presents multicollinearity which is a common occurance in machine learning. In practice, it is useful to identify and account for this phenomenon.